language: node_js
node_js: 12.18.3
branches:
  only:
  - dev
deploy:
  provider: heroku
  api_key:
    secure: DUDshPB4Jvhup9fXkiIuZQPdsUzmNUxA7KLzEAlvSUAL62EQdD5la1ahRaRKKgrgwbgHfiZ5AqqUg14uaeYjNJysj45cj3fg5jIKxE+VwB0NpkpmI7n3OjjIq93UZA2NYmR2OTCHHdzsVydcfB8rQpiZAcEvKz/3RBPRB8qyEyC8m+1y8iLf2Jby8esAS2ymqnluqPUSmMjOKZ2/e4tFbnDq0LhNDt/DHIFHjIFUdubcrTM9rCOJP/wolEflfw+9n+ZrOqC6oeBt3zpLjO4CNGpqomsDguvpikXRHxBEs4AT3TRcy6HfNCsMzrkBzb5jPWRc4EH5tbmbUQfedA8OEEijjxvxJ4aWW04Vzaby03kpAnYHaX62QDW6xV96PyoblkDjc7EgWpoGXhh3hzmPrC0CDuQALSEXDxfU1GwJDD7Ne+DGxfiubQYqog65kB/u4cghCyjqm4smsl0AWGKu482P2DeMCTKpmwSJxmBfk4PjuC/xrSBYX80VKepty0MO6ENBrhT8m0Rw+Kh3GaBOF9FoILgdp/5WoQ5VIp27WiPj2/60G7izZPwCu+IdWbG+AIYsPYqNTD17QnLLUuF/PvvV5DkpHFYSqk/+sJR10KXLpdfKVKECN/na+OVDarsvB9Q9csQotwBbOgvP9OoSTNBVJaTb2s2ygB6OaBA9GLM=
  app: alenvi-api-dev
addons:
  apt:
    packages:
    - mongodb-org
services: mongodb
notifications:
  slack:
    secure: p5fSAR+i1JRlPad91HVlu1WxAwztvPtbEUJ4480/mp5mPXtyBdxHyuHvwJ9k7cIfGN41CTrJV2+wnn8ivzpWq6eTLWNxwk0mF/l1mVtEHHvk+oXg3nBHtA9Rp1Pk5vPPDLhl0oHOLPveOuyiV8P4aQvP838qVC29/WldcJZA+uMVeOmNhha0anQmUQTKsTfa6wPUA0JvWEZ3pNFKR1HO2+uwuE8h/ZQjauTWY/DrMAMvX01mr9wlhop3Zpqq+cT+dq42ZI4mSI84EJ2mXNXhhTgRJMMiFF0GfBnCtLMwCBYP21pb4D8XGGpecUUW28G7gkiMuYaMDWmKPPJLowjYZhhVl+3W+jbC3RxxSLFI0hGbRsTXnE77UiE/nLENDg2Bsz+xsJ3cdsQN4eW1qHd+kSDUkYQb+NKAAHzNilba5n/vGtD3lHS3kTqDbhfq4ekFVcI0pahCM4KKYlu/wTqBeEdUoDAbkQo7boTH/Fq6fWlGDChxivwkULlphBhz52jJErF9IYC/5ZlNvVnVt6Pb3mLUEBk7aTsR+rRuYhOIPrLAU0fXAZhE1S42ltpvuWeHFgDWxdXo4ltMhOlcxaOzJu28jLHxS6laldIM245MdQ7/PjH3oeJ8UvRquEuNzmPqHA0oP90IFhiqSIS3sThV6Hzd5TpeT0ecTUPF7cKrC4I=
